### ISSUE TITLE
Standbild und Rausflug aus dem Spiel

### ISSUE THREAD

**Issue by Loraene** [ToadsworthLP/GronkhsLitW#1]
Seit 2.0 Fliege ich häufig aus dem Spiel nachdem ich mit Drawer aggiert habe oder Dinge platzieren wollte

**Comment by ToadsworthLP** [comment]
Bitte beschriebe die Ursache genauer. Erkläre bitte, welche Aktionen genau den Absturz auslösen.

**Comment by Loraene** [comment]
Gerade bin ich aus dem Spiel geflogen, nachdem ich ein Feld betreten haben, das Poison bei mir ausgelöst hat..... runtergeschaut... Spiel zu.

**Comment by ToadsworthLP** [comment]
Ich habe keine Versionsänderung bei Storage Drawers vorgenommen. Könntest du bitte einen Crash Report senden?

**Comment by Loraene** [comment]
Entschuldige bitte das ich erst jetzt antworte. 
Kannst du mir erklären, wie ich an einen Crash Report komme?
Dann würde ich dir den gerne zukommen lassen

**Comment by Loraene** [comment]
Außerdem bin ich heute wieder mehrfach mit dem gleichen Problem aus dem Spiel geflogen.
Beim letzten Mal hab ich eine Pipe auf eine schon angeschlossen ansetzen wollen und gleich Standbild ... Spiel zu.

**Comment by Loraene** [comment]
Ich hab jetzt eine Möglichkeit gefunden, das log auszulesen nun müßtest du mir bitte sagen wie ich es dir senden kann, hab hier nichts gefunden :) (den leider bin ich heute gefühlte hundertmal rausgeflogen (echte bestimmt 20mal)

**Comment by Loraene** [comment]
[techniclauncher_2016-07-03.txt](https://github.com/ToadsworthLP/GronkhsLitW/files/345129/techniclauncher_2016-07-03.txt)

**Comment by Loraene** [comment]
Ich hoffe es gibt eine Lösung für das Problem.
Denn ich finde das Modpack einfach nur Klasse und würde ungerne darauf verzichten :)

**Comment by Sadarex** [comment]
Ordner wo deine TechnicLauncher .exe liegt ->
\technic\modpacks\life-in-the-woods-extended\crash-reports

Die jeweils letzte .txt mit einem Absturz müsstest du hier hochladen :)

**Comment by Loraene** [comment]
Ich habs gefunden, allerdings komplett alles geschickt *schäm*, Allerdings sind da gleich am Anfang schon einige Abstürze mit Schwerwiegend aufgetreten

**Comment by Sadarex** [comment]
Options -> Video Settings -> Chunk-Loading

Steht das bei dir auf "Smooth"? Probier mal Default (NICHT Multi-Core)

**Comment by Loraene** [comment]
ok ich probier das mal aus .... danke :)

**Comment by ToadsworthLP** [comment]
Ich gehe mal davon aus, dass das Problem gelöst wurde :D
