### ISSUE TITLE
Wie viel Ram

### ISSUE THREAD

**Issue by Boston408** [ToadsworthLP/GronkhsLitW#10]
Moin Moin,

ich habe mal eine frage wie viel ist ram für einen externen Server nötig für das Mod Pack ? 
Habe das Mod Pack dezeit auf einen 2GB Ram Server laufen aber nach ca 1-2 Wochen fängt der Server an zu laggen an meinem System liegt es nicht habe 3,5 GB zugewiesen über den Technik Launcher. 

Danke schon mal im voraus für die Antwort und Ps. evtl hast du ja Lust mal eine Mindestest anforderung für das Mod Pack abzugeben in der Info ;)

**Comment by ToadsworthLP** [comment]
Wenn der Server laggt, musst du auch dem Server mehr RAM geben. Mit welchem Betriebssystem läuft der Server?

**Comment by ToadsworthLP** [comment]
Wegen Inaktivität schließe ich diese Issue. Falls du doch noch geplant hattest, zu antworten, erstelle bitte eine neue.
