### ISSUE TITLE
Absturz bei Installation

### ISSUE THREAD

**Issue by delsoll** [ToadsworthLP/GronkhsLitW#11]
Wenn ich versuche Life in the Woods über den Technic Launcher zu installieren, stürzt das Programm 
bei Phase 1 Schritt 2/7 ab. Also es tut sich dann einfach nichts mehr.
Der Crashlog :
http://pastebin.com/6ZzH7JwS

**Comment by Keith131** [comment]
Das ist auch mein Problem. Hoffentlich kommt bald eine Lösung

**Comment by delsoll** [comment]
Ich hoffe auch. Bin am verzweifeln

**Comment by MachiaPulcino** [comment]
Hi! Das Problem bestand bei mir auch, Habt ihr zufällig 32-bit Windows installiert als Betriebssystem?
Bei mir lag es nämlich daran. :)

**Comment by delsoll** [comment]
Nein habe ein 64 bit Windows 7

Am 29.06.2016 21:44 schrieb "MachiaPulcino" <notifications@github.com>:

**Comment by ToadsworthLP** [comment]
@delsoll Nein, du hast 32-bit Windows 7, sagt zumindest der Log. Du hast auch nur 1GB RAM zugewisen, ändere das bitte über die Launcher-Einstellungen unter Java-Einstellungen.

**Comment by delsoll** [comment]
Danke für die schnelle Antwort. Werde es gleich ausprobieren

Am 30.06.2016 09:53 schrieb "ToadsworthLP" <notifications@github.com>:

**Comment by delsoll** [comment]
Ich kann in den Einstellungen nicht mehr als 1 GB freigeben.

**Comment by ToadsworthLP** [comment]
Weil der Technic Launcher unter 32-bit Windows nicht mehr als 1 GB ansprechen kann. Da kann ich nichts machen.

**Comment by delsoll** [comment]
Könnte ich mehr RAM zuweisen wenn ich ein 64 bit Linux emuliere?

Am 02.07.2016 10:45 schrieb "ToadsworthLP" <notifications@github.com>:
