### ISSUE TITLE
Fatal Error wenn jemand stirbt

### ISSUE THREAD

**Issue by Veraatversus** [ToadsworthLP/GronkhsLitW#12]
Wenn jemand stirbt bekommen zufällige Leute auf dem Server Fatal Error und somit Disconnect.
das Problem trat bisher nicht im Singleplayer über den Launcher auf sondern nur bei der Serverversion.
Die Serverkonsole meldet mir folgendes:
http://pastebin.com/8bThftx6

**Comment by LMBlackWolf** [comment]
Kann ich bestätigten, bei mir sind es allerdings alle Personen die sich in der Nähe von dem gestorbenen befinden.

Serverconsole:
http://pastebin.com/wU8XZXQ5

**Comment by LMBlackWolf** [comment]
Auch mit Version 2.2 disconnecten Leute wenn jmd stirbt. 
Wenn man die Gravestone-Mod von Version 2.0 verwendet (GraveStones-1.7.2_1.4.jar) dann geht es wieder.

**Comment by ToadsworthLP** [comment]
Ich werde mir das am Wochenende mal ansehen, hab nur unter der Woche wie immer da keine Zeit. Diese Woche kommt das Update warscheinlich Samstags oder Sonntags, da sollte das gefixt sein. Wichtig: Den Server auch neu installieren (also alles bis auf den "world" Ordner löschen!), falls es einer ist!

**Comment by ToadsworthLP** [comment]
Nutzt man die Gravestones-Version aus 2.0, werden Baubles-Items nicht unterstützt. Ich schaue dennoch, ob sich da etwas machen lässt. Ich schreibe dich privat an, wenn es etwas neues dazu gibt, allerdings sieht es im Moment nicht danach aus.
