### ISSUE TITLE
Spiel stürtzt sofort ab

### ISSUE THREAD

**Issue by Flowerstripes** [ToadsworthLP/GronkhsLitW#13]
Hi,
Finde das Modpack ganz gut, aber nach einiger Zeit spielen, stürtzt das spiel sofort nach spawnen der spielerfigur wieder ab. kann mir da jemand helfen. danke

**Comment by ToadsworthLP** [comment]
Ohne Crash Report kann ich da nichts machen. Lade ihn bitte auf Pastebin oder so hoch und schick dann einen Link.

**Comment by Sadarex** [comment]
Options -> Video Settings -> Chunk-Loading

Sollte das bei dir auf "Smooth" stehen probier mal "Default" (NICHT Multi-Core)

**Comment by ToadsworthLP** [comment]
Ich werde das beim (warscheinlich morgigen) Update auf Default vor-einstellen, weil anscheinend echt viele Leute das Problem haben.
@Sadarex Bist ja hier schon so eine Art Supportmitarbeiter :D
