### ISSUE TITLE
Update von Life in the Woods?

### ISSUE THREAD

**Issue by Kalimbo** [ToadsworthLP/GronkhsLitW#14]
Dies ist keine Fehler Meldung sondern eher eine Frage.

Also zur Frage.

Es ist jetzt ja ein Update raus gekommen für Life in the Woods (1.1.5) dort wurden ja interessante Dinge hinzugefügt und wichtige Sachen gepacht (Mega Plant Pack zum Beispiel). Meine Frage an dich ist also. Spielst du dieses Update bald auf oder erst wenn es "Gronkh" erwähnen würde. Ich denke mal das die Leute die deine Mod Spielen es begrüßen würden wenn dieses Update so schnell wie möglich auch für uns verfügbar wäre :)

Eine Antwort wäre super.

Danke auch für deine Arbeit und die Zeit die du da reinsteckst. Top!!!

Bis denne Kalimbo

**Comment by Sadarex** [comment]
Dem würde ich mich anschließen.

Wäre super wenn das Pack daraufhin geupdated werden würde, ohne das Gronkh es auch hat.

**Comment by ToadsworthLP** [comment]
Werde ich in das für nächstes Wochenende angesetzte Update packen.

**Comment by Sadarex** [comment]
Biete mich gerne als Beta-Tester an :)
Skype: kamikaze-phoenix

**Comment by ToadsworthLP** [comment]
@Sadarex Würde nur leider nicht viel bringen, weil ich die meisten Updates direkt über den TechnicLauncher teste, d.h. ich ändere einfach den Link zu der Datei des Modpacks. Im Prinzip könnte jeder mit viel Glück, der gerade das Pack installiert, ganz einfach die Beta spielen. Die Update-Mitteilung sende ich erst, wenn ich getestet habe, aber auch davor ist es daher eine offene Beta ;D Aber wenn du willst (und ich es nicht vergesse), kann ich dir ja schreiben, wenn ich die neue Version hochgeladen habe.

**Comment by Sadarex** [comment]
@ToadsworthLP Sehr gerne :)

**Comment by Kalimbo** [comment]
Super danke ToadworthLP. Ich warte sehnsüchtig dann auf das Update :D

**Comment by immertroll** [comment]
Kurze Frage. Kann ich im Technic Launcher wieder auf eine alte Version zurück gehen? Wenn einmal die neue installiert wurde, konnte man bisher nicht zurück. Zumindest habe ich keinen Weg gefunden.

**Comment by ToadsworthLP** [comment]
@immertroll Da ich das Modpack nicht über Solder hoste, gibt es auch keine Möglichkeit dazu. Falls du Probleme mit der neueren Version hast und deshalb auf die älteren Versionen zurückwillst, öffne bitte eine Issue für dein Problem!
PS: Beeil dich aber, mein Patch Day ist üblicherweise Samstags!
