### ISSUE TITLE
Fehlende Mods (bis Folge 135)

### ISSUE THREAD

**Issue by Sadarex** [ToadsworthLP/GronkhsLitW#15]
Moin,

aktuell fehlen die Mods:

MineFactoryReloaded
&
FloodLights

Die habe ich vorübergehend bei mir von Hand nachinstalliert und der Server ist stabil.

Gruß Sadarex

**Comment by ToadsworthLP** [comment]
Mir ist das bewusst, bin nur gerade auf Urlaub, und mein Internet ist nicht gut genug, um 200MB für Clienz und Server hochzuladen. Das Update kommt warscheinlich irgendwann nächstes Wochenende ;)

**Comment by ToadsworthLP** [comment]
*Client
Schreibe das hier gerade am Handy
