### ISSUE TITLE
Fehlende Animationen (1.2.3 -> 2.1)

### ISSUE THREAD

**Issue by Sadarex** [ToadsworthLP/GronkhsLitW#16]
Moin,

seit dem Update von "1.2.3" auf "2.1" fehlen bei mir ein paar Animationen.

z.B. das grüne "Aufleuchten" wenn ich Pflanzen Dünge.

Gruß Sadarex

**Comment by Kalimbo** [comment]
Ich habe heute erst Bäume mit Knochenmehl befeuert nenne ich es mal. Und dort kam dieses grüne Leuchten. Also bei den Bäumen klappt es jedenfalls :)

**Comment by Sadarex** [comment]
Ok sry für die Aufregung?^^ 

Die fehlenden Animationen an anderen stellen haben sich irgendwie selbst gelöst. Evtl. lags an der MystCraft initialisierung?

Das "düngen" funktioniert mit Knochenmehl normal und mit dem Garden Core Dünger fehlt die Animationen. Das ist vermutlich normal.

/closed
