### ISSUE TITLE
Java Arbeitsspeicher -> Ladeprobleme

### ISSUE THREAD

**Issue by Adaadena** [ToadsworthLP/GronkhsLitW#17]
Hi,
Ich habe sehr lange Ladezeiten und dann startet das Spiel teilweise doch nicht. 
Kann es daran liegen, dass ich nur 1GB Arbeitspeicher im Launcher zugewiesen habe?
Wenn ja, habe ich das Problem, dass ich im technicklauncher nur werte kleiner gleich 1GB auswählen kann.
Woran kann das liegen?

**Comment by Kalimbo** [comment]
Du gehst auch bei dem Technik Launcher auf?

Oben Rechts -> Launcher-Optionen -> Java Einstellungen -> Arbeitsspeicher

Da schaust du nach wegen Arbeitsspeicher Einstellungen? Bei mir geht es bis 15 GB, da mein Rechner 16 GB Arbeitsspeicher hat. Hast du dann vllt. nur 2 GB Arbeitsspeicher? 

Vllt. ist dein Rechner so alt und du hast nur so wenig Arbeitsspeicher? 

Schau da erstmal nach

Bis denne Kalimbo

**Comment by Adaadena** [comment]
Danke für die flotte Antwort. Ich habe mich mal ein bisschen durchwurstet und habe eine ältere JAVA version runter geladen. Dann konnte ich auch mehr Arbeitspeicher auswählen. LAg also nicht an der Mod sondern am launcher/JAVA. 
Jetzt funktioniert alles wieder :)

**Comment by Sadarex** [comment]
Vermutlich hattest du nur 32bit installiert. Für Minecraft sollte zwingend 64bit Java installiert sein.
