### ISSUE TITLE
Chunk-Loading "Smooth" = Absturz

### ISSUE THREAD

**Issue by Sadarex** [ToadsworthLP/GronkhsLitW#18]
Seit dem Wechsel von 1.2.3 auf 2.1 stützt das Spiel direkt ab wenn das Chunk-Loading auf Smooth steht.
[crash-2016-07-03_17.19.50-client.txt](https://github.com/ToadsworthLP/GronkhsLitW/files/345132/crash-2016-07-03_17.19.50-client.txt)

Siehe auch: https://github.com/ToadsworthLP/GronkhsLitW/issues/1

**Comment by ToadsworthLP** [comment]
Das ist ein bekanntes Problem auf einigen Systemen. Auf meinem Testrechner läuft es z.B ohne Probleme (Kenne aber jemanden, der auch dieses Problem hat). Wenn es funtioniert, lädt die Welt um einiges besset, wenn nicht, muss man es eben ausschalten, was jetzt auch nicht sonderlich schwer ist ;)
PS: Ich lasse diese Issue offen, damit ich hoffentlich beim nächsten Update daran denke, Chunk Loading als Default voreinzustellem.
