### ISSUE TITLE
Probleme mit der Steuerung

### ISSUE THREAD

**Issue by immertroll** [ToadsworthLP/GronkhsLitW#19]
Erstmal danke für das gute Modpack. Es erleichtert die Installation des Servers ungemein.

Leider habe ich am Client aktuell die Probleme, dass ich sofort an die Decke oder den Boden schaue, sobald ich die Maus bewege. Es springt einfach immer hin- und her.

Kennt jemand den Bug oder hat vielleicht sogar direkt eine Lösung?

Danke

**Comment by ToadsworthLP** [comment]
Probier mal, die Mausempfindlichkeit in den Controls runterzustellen

**Comment by ToadsworthLP** [comment]
Ups, falscher Button

**Comment by immertroll** [comment]
So mit der aktuellen Version 2.2 ist das Problem erledigt. Woher auch immer die Lösung gekommen ist.
