### ISSUE TITLE
Viele Crashes

### ISSUE THREAD

**Issue by DieDreiBeiden** [ToadsworthLP/GronkhsLitW#20]
Server+Client crashen seit 2.1 wesentlich öfter. Ich werde hier mal ein Paar Crashreports posten. 

Client:
http://pastebin.com/XrMcsQna
http://pastebin.com/ACSg2iX4
http://pastebin.com/U530xCXx
http://pastebin.com/4aUxUXhW
http://pastebin.com/3PpKsSMz
http://pastebin.com/HGKpyrLb
http://pastebin.com/UrVdwun5

Server:
http://pastebin.com/nEJxhiFE
http://pastebin.com/gWxEh02A
http://pastebin.com/0RqahkqN

**Comment by DieDreiBeiden** [comment]
Kann auf Nachfrage gerne noch mehr zur Verfügung stellen.

**Comment by ToadsworthLP** [comment]
Hat Version 2.2 es gefixt?

**Comment by DieDreiBeiden** [comment]
Die ersten Tests übersteht er soweit ganz gut. Sobald wieder Crashes vorkommen, werde ich hier wieder die Reports posten. Danke für das Update!

**Comment by DieDreiBeiden** [comment]
Und es geht wieder los :/ Server bleibt bisher stabil, nur der Client fängt wieder an.

http://pastebin.com/eUrSAKfU
http://pastebin.com/1zwLbVcT
http://pastebin.com/wakgv9wT
http://pastebin.com/3bR4huFd
