### ISSUE TITLE
Server Crash 2.2

### ISSUE THREAD

**Issue by DieDreiBeiden** [ToadsworthLP/GronkhsLitW#21]
Server crasht beim Startup

http://pastebin.com/NcgwhWCe
http://pastebin.com/JcDUVhp3
http://pastebin.com/w0Cgim55

**Comment by Vadril** [comment]
Kann ich so auch bestätigen, habe genau das gleiche Problem.

**Comment by ToadsworthLP** [comment]
Beim Update auf Version 2.2 wurde auch Forge noch einmal geupdated. Um einen Client auf Version 2.2 mit dem Server zu verbinden, müssen die alten Serverdateien gelöscht, der Server erneut heruntergeladen und installiert werden. Der Spielstand kann beibehalten werden, indem man den "world"-Ordner einfach nicht löscht ;D

**Comment by Vadril** [comment]
Hi,
genau das habe ich getan, hatte allerdings das gleiche Problem zur Folge wie oben von DieDreiBeiden erwähnt.

**Comment by DieDreiBeiden** [comment]
Hast du den Server noch mal neu runtergeladen?
