### ISSUE TITLE
Performance Probleme

### ISSUE THREAD

**Issue by immertroll** [ToadsworthLP/GronkhsLitW#22]
Der Version 2.2 läuft zwar viel stabiler und der Steuerungs-Bug ist behoben, allerdings ist Performance jetzt grottig. Kann das durch ein neu hinzugekommenes Mod kommen?

Zuvor hatte ich 50-60fps mit mittleren Sidur Shadern. Jetzt sind es so um die 20fps.

**Comment by ToadsworthLP** [comment]
Ich habe einige Voreinstellungen geändert, weil einige Optimierungsmaßnahmen auf manchen PCs für Probleme sorgen. Die üblichen Kandidaten sind da z.b. Smooth Lighting, das, wenn man mit einem Shader spielt, nicht stark sichtbar ist. Das kann man auf "Minimum" bzw. 20% stellen, und spart sehr viel Performance. Probiere etwas in den Grafikeinstellungen herum, da gibt's leider keine universelle Strategie.

**Comment by Veraatversus** [comment]
hatte ein ähnliches Problem und habe es nun in den griff bekommen indem ich in den Grafikeinstellungen unter Animationen die Terrain Animation ausgestellt habe. ich habe mich dann eher für die fps statt der Bewegung entschieden ;)
