### ISSUE TITLE
Spiel speichert nicht die Sound Einstellungen

### ISSUE THREAD

**Issue by Kalimbo** [ToadsworthLP/GronkhsLitW#24]
HeyHo,

ich habe das Problem das Minecraft immer wieder die (Musik) Atomsphäre/Umgebung auf 100% hoch stellt. Man kann es gerne testen indem man ins Wasser springt und einmal taucht. Danach ist es auf jeden Fall wieder hoch gestellt. 

Gibt es eine Möglichkeit das Minecraft nicht immer dies wieder Automatisch auf 100 % stellt? 

Vielen dank im voraus :)

**Comment by ToadsworthLP** [comment]
Dieser Fehler ist mir unbekannt - ich werde ihn austesten und wenn möglich im dieswöchigem Freitagspatch (der diesmal warscheinlich am Samstag stattfindet) beheben.

**Comment by DieDreiBeiden** [comment]
Kann ich so bestätigen, die Umgebungs Einstellung setzt sich immer wieder neu auf 100% zurück.
