### ISSUE TITLE
Crash bei der Benutzung der Mod. Growcraft

### ISSUE THREAD

**Issue by Meriones** [ToadsworthLP/GronkhsLitW#25]
Hi Toadsworth

Danke für dieses Mod.Pack. Ich würde gerne zusätzlich diese Mod hier benutzen. Growcraft Mod http://mods.curse.com/mc-mods/minecraft/235092-growthcraft-community-edition#t1:other-downloads.
Ich benutze die neuste Version.

Leider stürtzt Minecraft jedesmal ab. Hier ist der CrashReport. Wäre schön wenn du sie zum laufen bekommen könntest. 

http://pastebin.com/VKwGnQ8X

Danke für deine Zeit und Mühe

Gruss Meriones

**Comment by ToadsworthLP** [comment]
Tut mir leid, aber für modifizierte Versionen des Modpacks kann ich im Moment wegen Zeitmangels keinen Support zur Verfügung stellen. Am Wochenende kann ich mich vielleicht drum kümmern.

**Comment by Meriones** [comment]
Danke dir für deine schnelle Antwort. Mach dir da mal keinen Stress wegen. Ich bin nicht davon ausgegangen das das jetzt sofort passiert, wenn es passiert. Natürlich nur wenn du mal Zeit und vor allem Lust hast. 

Nochmal danke und einen schönen Abend noch.
 

    ToadsworthLP <notifications@github.com> schrieb am 20:18 Donnerstag, 14.Juli 2016:
 

 Tut mir leid, aber für modifizierte Versionen des Modpacks kann ich im Moment wegen Zeitmangels keinen Support zur Verfügung stellen. Am Wochenende kann ich mich vielleicht drum kümmern.—
