### ISSUE TITLE
Hauptmenü ist einfach weiß

### ISSUE THREAD

**Issue by Milofax** [ToadsworthLP/GronkhsLitW#26]
Hallo!
Leider sehe ich bei meinem Mac mit el Capitan installiert beim Start nur einen weißen Bildschirm und die Musik läuft im Hintergrund. Ich benutze die neueste Version 2.2

**Comment by ToadsworthLP** [comment]
Könntest du bitte einen Screenshot und den Log schicken? Klingt nach einem Fehler mit OpenGL, aber wie gesagt, ich brauch den Log.

**Comment by Milofax** [comment]
[Archiv.zip](https://github.com/ToadsworthLP/GronkhsLitW/files/368640/Archiv.zip)

Wie gesagt, der Screen ist einfach komplett weiß ( die Musik läuft) ich habe Dir mal die Logs angehängt. Ich nutze die 2.3er Version.

**Comment by philippu2006** [comment]
Hier mal ein Log da ich das gleiche Problem habe. Habe sogar in Parallels ein ganz frisches OS aufgesetzt und selbst da gibt es den Fehler.
Mittlerweile hat es sich aber von einem weissen Bildschirm wo man die Minecraft Musik hört und die nicht sichtbaren Schaltflächen dennoch anklicken kann (man hört den Klickten für die Buttons in Minecraft) in ein abstürzen sofort nach dem Start geändert.
Also man klickt auf Spielen und danach stürzt es ab.
[techniclauncher_2016-07-24.log.zip](https://github.com/ToadsworthLP/GronkhsLitW/files/380224/techniclauncher_2016-07-24.log.zip)

**Comment by philippu2006** [comment]
Hast du denn die Logs schon mal durchgesehen?
