### ISSUE TITLE
Fehlende Blocks mit Update 2.3

### ISSUE THREAD

**Issue by Dracan84** [ToadsworthLP/GronkhsLitW#27]
Hallo ToadworthLP,

vielen dank das du dir die Mühe machst und die Mods zusammenstellst.
Habe seit heute morgen das neue Update auf 2.3 gepatched. Jetzt bekomme ich beim starten meiner MineCraft welt das Forge 48 Blocks nicht finden kann.
Habe natürlich vorher ein Backup gemacht. Wenn ich den Dialog mit ja bestätige wird die Welt geladen aber die Blöcke sehen extrem verpixelt aus. So sahen Sie vorher nicht aus. Und ich glaube die Mod für den Chisel wird irgendwie nicht geladen. Auf jedenfall sehe ich die gechilsete Erde nicht mehr. Sie ist Durchsichtig. Modpack löschen und neu herunterladen hat leider nichts gebracht. Hast du vielleicht noch eine Idee? Habe vorher immer mit der Version 2.1 gespielt da war alles ok.

Vielen Dank für deine Mühe!
Dracan

**Comment by ToadsworthLP** [comment]
Schon mit dem Update von 2.1 auf 2.2 wurde Underground Biomes Constructs geupdated, mit diesem Update wurde von 32x32 Texturen auf 16x16 umgestellt. Da dieses Update aber auch Fixes enthält, werde ich nicht downgraden. Wegen der Chisel-Sache, kannst du bitte den Log posten?

**Comment by Dracan84** [comment]
Die Log aus dem .technic Ordner?

**Comment by Dracan84** [comment]
Das mit den Textuen ist ja blöd. Da kann man dann ja nichts machen. Mir ist dann noch aufgefallen das ich die Zimmermannsblöcke wenn sie mit einem Stein überzogen sind nicht mit einer Spitzacke entfernen kann. Und die Chisel Erde kann ich auch nicht mit einer Schaufel oder ähnlichem Gegenstand entfernen. 

Vielen Dank für deine schnelle Antwort!

**Comment by Dracan84** [comment]
Hey ToadsworthLP,

das mit dem Chisel Blöcken liegt wohl daran das ich unter den Grafikeinstellungen die berechnung der Chunks auf Multi-CPU umgestellt habe. Wenn es auf Default steht sieht man sie wieder. Sind aber nicht abbaubar. Und die Frames sind grausam 2-6 Frames, statt üblicherweise 30-40

**Comment by Veraatversus** [comment]
Das Problem kenne ich auch bei speziell gedrechselten Blöcken. Diese sind aber weiterhin da nur eben die Textur ist eben unsichtbar.  Wenn ich einen nahegelegenden Block verändere klappt es kurzzeitig, aber nicht lang.

Lösung scheint zu sein eben das Chunk Loading nicht auf Multi-Cpu zu haben.
Und wegen der Performance könnte ich nur raten in den Grafikeinstellungen unter Animationen die Terrain Animation auszuschalten.

**Comment by Dracan84** [comment]
das möchte ich ungerne machen, Spielen bei 2-5 FPS macht keinen spass. Am besten würde es mir gefallen wenn man wieder die Version 2.1 herunterladen könnte. Da hat alles funktioniert

**Comment by ToadsworthLP** [comment]
Die Hardwareanforderungen steigen mit jedem Update, weil immer mehr Mods hinzukommen. Ich möchte mein Modpack hier möglichst genau Gronkh's Setup entsprechen lassen, deswegen kann ich nicht einfach Mods weglassen. 2.1 ist nicht mehr verfügbar, weil ich das Modpack nicht über Solder hoste, aber die Dateien kann man immer noch herunterladen:
Client: http://adf.ly/1cU3hr
Server: http://adf.ly/1cU3k0
Um den Client zu installieren, gehst du ins Verzeichnis des Modpacks, löscht die Ordner config, liteconfig, mods, resourcepacks, resources, scripts und shaderpacks, und ziehst dann die gleichnamigen Ordner aus der Client-Zip heraus. Ohne löschen draufziehen & ersetzen geht NICHT.
