### ISSUE TITLE
Rezepte nicht mehr sichtbar

### ISSUE THREAD

**Issue by immertroll** [ToadsworthLP/GronkhsLitW#29]
Bis Version 2.1 konnte man auf der rechten Seite des Inventars die ganzen verfügbaren Items einsehen und bei Klick das Rezept anzeigen. Seit Version 2.2 wird bei einem Klick immer gleich ein 64er Stack in das Inventar gelegt. Wie komme ich denn nun zu den Rezepten?

Danke ;-)

**Comment by ToadsworthLP** [comment]
Wenn Cheats erlaubt sind, dann wird ein 64er-Stack ins Inventar gelegt. Du kannst dieses Verhalten über die NEI-Optionen im unteren, linken Rand des Inventarbildschirms ändern.

**Comment by ToadsworthLP** [comment]
Alternativ kannst du auch eindach mit dem Mauszeiger über ein Item fahren und "R" drücken ;D

**Comment by immertroll** [comment]
Super danke. Endlich geht das wieder. ;-)
