### ISSUE TITLE
Ältere Versionen des Client/Servers

### ISSUE THREAD

**Issue by xcy7e** [ToadsworthLP/GronkhsLitW#33]
Hallo lieber Toadsworth!!!

Super sache mit dem Pack, aber könntest du **bitte bitte bitte bitte**(!) die _alten Versionen auch noch zum DL bereitstellen_? Ich kann den Sharepoint-Link nicht entschlüsseln und komme stets nur an die neuesten Update-Packs, aber nicht an ältere Versionen.. (In meinem Fall brauche ich die Server-Version 2.1) aber andere profitieren davon sicher auch ! :)

Keep up the good work m8

**Comment by ToadsworthLP** [comment]
Ich hoste das Pack nicht über Solder, deswegen ist der Download nicht über den Launchet möglich. Aber man kann die älteren Versionen immer noch runterladen:
Client: http://adf.ly/1cU3hr
Server: http://adf.ly/1cU3k0
Um den Client zu installieren, gehst du ins Verzeichnis des Modpacks, löscht die Ordner config, liteconfig, mods, resourcepacks, resources, scripts und shaderpacks, und ziehst dann die gleichnamigen Ordner aus der Client-Zip heraus. Ohne löschen draufziehen & ersetzen geht NICHT.

**Comment by ToadsworthLP** [comment]
Ich gehe mal davon aus, dass das Problem hiermit behoben ist, deshalb schließe ich diese Issur mal

**Comment by xcy7e** [comment]
Ja das ist er! Vielen lieben **Dank** lieb**e**r **Toadsworth**!!!
Wenn du mal Lust & Zeit hast könntest du ja mal ein paar der letzten Versionen in einem der Beschreibungstexte Listen und Verlinken, darüber würden sich sicher ein paar mehr Leute freuen.
