### ISSUE TITLE
Ein paar Items lassen sich nicht nutzen

### ISSUE THREAD

**Issue by DTMMigen** [ToadsworthLP/GronkhsLitW#34]
Hallo ToadsworthLP,

zuerst einmal vielen dank das Du dir soviel Arbeit für uns alle machst.

Leider muss ich Dich um Hilfen bitten. Bei der Mod Thermal Foundation ist es leider nicht möglich die Metalle zu Pulver zu verarbeiten, so das keine Legierungen geschmolzen werden können (z.B. Bronze).
Weder mit einer Mühle noch mit einem Mörser. 

mit bestem Gruß

Migen

**Comment by ToadsworthLP** [comment]
Es ist leider sehr schwer, den Überblick über Gronkh's Setup zu behalten, weil er die Mod-Liste in seiner Videobeschreibung schon lange nicht mehr aktualisiert. Ich bin deshalb genau wie alle anderen auch, darauf angewiesen, was direkt sichtbar ist. Anscheinend habe ich eine (oder mehrere) Mods übersehen. Ich kann aus zeitlichen Gründen auch nicht jede Folge schauen, deswegem kann sowas passieren. Wenn du mir den Namen des Items/Blocks sagst, den Gronkh dafür benutzt, kann ich die entsprechende Mod hinzufügen. Vergangenes Wochenende hatte ich nur leider keine Zeit wegen der Better than Minecon, aber nächstes Wochenende (warscheinlich Samstag) gibt's wieder einen Patch.

**Comment by ToadsworthLP** [comment]
Update: Weil ich solche Fragen häufiger bekomme, habe ich nun einen offiziellen Anlaufpunkt für fehlende Mods erstellt: http://adf.ly/14077095/modtracker
Oder schreib mir einfach in welcher Folge Gronkh das macht, dann kann ich selbst nachsehen.

**Comment by DTMMigen** [comment]
Alles klar vielen dank, sobald ich kann schau ich mir mal die Mod genauer
an vieleicht fällt mir ja was auf.
Was Gronkg sein LP angeht hänge ich ehrlich gesagt ein paar Folgen
hinterher.

MfG Micha

Am 06.08.2016 10:19 AM schrieb "ToadsworthLP" <notifications@github.com>:
