### ISSUE TITLE
Buildcraft Machines

### ISSUE THREAD

**Issue by ibouu** [ToadsworthLP/GronkhsLitW#36]
Hi,

danke für das geniale Paket!!

Mir ist aufgefallen, dass die Buildcraft-Maschinen und jede Menge weitere Dinge von Buildcraft fehlen, oder nicht funktionieren.. Könntest du dir das bitte mal ansehen?

lg

**Comment by ToadsworthLP** [comment]
In welcher Folge hat man gesehen, dass Gronkh sie hat? Eigentlich hat er ja nur die Core und Transport-Module installiert, aber vielleicht hat er die anderen off-cam hinzugefügt.
