### ISSUE TITLE
"Building Terrrain" Crash

### ISSUE THREAD

**Issue by TheDobby** [ToadsworthLP/GronkhsLitW#37]
Heyo.
Hab mir das Spiel runtergeladen. Kann es bloß nicht spielen :/
Ich kann es starten (Fenster oder Fullscreen) und auf "Create New World" klicken, und danach ist Ende.
Er lädt sich zu Tode, und nach "Building Terrain" geht LitW aus. Ohne Fehlermeldung.
Was da loooos? xD

LG 
Dobby

**Comment by Schiebo** [comment]
Habe das Problem auch. Wenn ich auf den Server von nem Kumpel joine lädt er sich auch zu tode und schließt das Spiel. Würde mich mal interessieren woran es liegt. Das normale LitW macht nämlich keine Probleme.

**Comment by protoneutron** [comment]
Im Technic Launcher bei Launcher Options Java mind. 3GB zuweisen. Hat bei mir das Problem gelöst!
