### ISSUE TITLE
Spiel stürtzt ab wenn ich in denn singelplayer joine.

### ISSUE THREAD

**Issue by RI3SI3Tv** [ToadsworthLP/GronkhsLitW#39]
Crash wenn ich im singelplayer eine welt starte. Keine ahnung warum. kann mir jemand helfen?

**Comment by Vapor028** [comment]
Nur beim ersten generieren oder immer? Hatte vorher das selbte Problem. Neue Welt im Singleplayer generiert und danach einen Absturz. Anschließend ging alles wunderbar.
