### ISSUE TITLE
Performance und RAM Probleme seit UPDATE

### ISSUE THREAD

**Issue by HelbosWelt** [ToadsworthLP/GronkhsLitW#40]
Hi,

ich hab früher als Erik angefangen hat (also vor 200 Tagen?) LITW gespielt. hatte da ne Welt, hatte alle Einstellungen auf möglichst hoch gesetzt und hatte keinerlei lags im Dschungel-Biom

Ich habe jetzt dein Pack geladen, nachdem schon seit dem letzten LITW update nix mehr richtig lief.
Ich habe folgende Beobachtung gemacht: Nach etwa 20 Minuten Spielzeit, besonders beim setzen mehrere Blöcke oder beim erkunden läuft Stück für Stück der RAM bis etwa 12gb voll (16gb zugewiesen) , ab etwa 10gb sinkt die fps-zahl von 60 auf unter 15 und bleibt irgendwann stehen, danach crasht das Spiel ohne Fehlermeldung. (bei alten Welten und neu erstellten)

Es macht keinen Unterschied welchen Shader ich nutze oder ob ich jetzt auf fancy mit Sichtweite far oder fast mit Sichtweite short spiele. Chunkloader ist auf smooth. Ich habe schon einiges getestet. Meistens hilft nur ein kompletter Spielneustart.

Ich starte vom Launcher aus.
Ich habe ne GTX 980, 32gb RAM, ein I7-4770k und das Spiel läuft von meiner Aufnahmeplatte aus, sollte also wohl auch da kein Flaschenhals geben. Irgend eine Idee?

**Comment by protoneutron** [comment]
Weise Java im Launcher mal maximal 4 GB zu. Zu viel zugewiesener RAM kann sich negativ auf die Performance und Stabilität auswirken. Schau außerdem mal nach, ob du die 64bit Version von Java installiert hast.
Hoffe ich konnte helfen.

**Comment by SgtGlattbart** [comment]
Auch hier mal der Tipp von mir:

Moin.

Ich habe auch noch eine Idee, die ihr nutzen könnt:

Ich hatte selbst auch extreme FPS Probleme in Minecraft mit diesem PC:
i7-860
8GB RAM
XFX 6950 2GB

Durc ein paar englische Foren und rumprobieren konnte ich das dann auf die Grafikeinstelung
"Terrain Animated" eingrenzen. Diese findet ihr in den Grafikeinstellungen unter "Animations".

Dan sprang meine FPS von auch 10-20 auf 60 und mehr.
