### ISSUE TITLE
Extreme FPS Probleme

### ISSUE THREAD

**Issue by Sparibua** [ToadsworthLP/GronkhsLitW#42]
Systeminfos:

Windows 10
i5-3470
HD Radeon 7900
8 GB Ram (4GB für Java freigegeben und werden auch 1,5GB ca genutzt)

Habe extreme FPS Probleme (immer zwischen 2 und 10 FPS), obwohl ich keinen Shadder aktiviert habe und View Distance auf 2 eingestellt habe. CPU Auslastung ist zwischen 40-50 und GPU  auch knapp unter 40%. Alle anderen Spiele (The Witcher,Fallout 4...), auch das normale Minecraft funktionieren problemlos.

Ich hoffe mir kann jemand helfen, ich habe keine Ahnung was ich noch machen soll.

**Comment by protoneutron** [comment]
Kann das Problem bedingt bestätigen!

Evtl eine Lösung für dich, da deine Grafikkarte denselben Treiber nutzt wie meine:

Hatte genau wie du egal ob mit oder ohne Shader und egal welche Sichtweite 2-8FPS.
Da hatte ich den Grafiktreiber Crimson Edition 16.9.1 Hotfix. Testweise mal den älteren **Crimson Edition 16.7.3** installiert (**Clean Install!**) und ich hatte tatsächlich mit ausgestelltem Shader 30-40FPS.
Allerdings wegen World-Updates starke Lag-Spikes. Muss wohl an einem/mehreren Mods liegen.

Mit Extreme Shader und 12 Chunks Sichtweite bekomme ich max. 10 FPS. Sichtweite reduzieren und Shader ausstellen bringt ein paar FPS mehr. Das Lagometer schlägt bzgl. World-Updates stark aus (s. Bild)

![2016-09-21_13 13 01](https://cloud.githubusercontent.com/assets/22344081/18708987/045c607e-7ffe-11e6-8844-6e19cad7a2c3.png)


(Modpackversion 2.4)
Rig:
Win 10 x64
i5-2500k
Radeon R9 280X
4GB RAM Java zugewiesen (JRE 8 x64 Update 101)

**Comment by SgtGlattbart** [comment]
Moin.

Ich habe auch noch eine Idee, die ihr nutzen könnt:

Ich hatte selbst auch extreme FPS Probleme in Minecraft mit diesem PC:
i7-860
8GB RAM
XFX 6950 2GB

Durc ein paar englische Foren und rumprobieren konnte ich das dann auf die Grafikeinstelung
"Terrain Animated" eingrenzen. Diese findet ihr in den Grafikeinstellungen unter "Animations".

Dan sprang meine FPS von auch 10-20 auf 60 und mehr.
