### ISSUE TITLE
Tinkers is still missing

### ISSUE THREAD

**Issue by badenzer** [ToadsworthLP/GronkhsLitW#49]

**Comment by ToadsworthLP** [comment]
I stopped maintaining the project a few months ago. This isn't the end, however, as it may get revived later. The same actually happened before the 2.0 update, as soon as I finish the personal project I'm currently working on, I may get back to this.

**Comment by rsalevsky** [comment]
I don't find another way to contact you but are you interested in some collaboration? I'm interested in doing some fixes and adding the missing mods.  You can checkout my GitHub profile and if you are interested feel free to contact me via the mail address in my profile.

**Comment by shadowcryyy** [comment]
pls tell me how can i do in the mod pack tinkers or pls update the modpack from gronkh thank

**Comment by ToadsworthLP** [comment]
@rsalevsky If you can send me a complete list of every mod that Gronkh ever added to vanilla LitWR I could do an update. Finding the mods that he has added is actually the most tedious part of an update, not the update itself.

**Comment by SgtGlattbart** [comment]
@ shadowcryyy
When you want to add Tinkers Construct, then you just have to download the appropriate version of this mod for 1.7.10 and add it to the 'mods' folder in the life in the woods-extendes profile/directory.

**Comment by SgtGlattbart** [comment]
@ToadsworthLP 
Kannst du eventuell diese Liste für die Mods nutzen?
https://gronkh-wiki.de/wiki/Let%27s_Play_Life_in_the_Woods#Verwendete_Mods_und_Texture_Packs

Das ist ja angeblich mit Stand Folge 330 sehr aktuell.

**Comment by rsalevsky** [comment]
@ToadsworthLP Ich kann dir das offiziell modpack was Gronkh im live-stream veröffentlicht hat zukommen lassen. Da sollte alles drin sein was du brauchst...

**Comment by ToadsworthLP** [comment]
Ich habe das Pack von Grund auf neu zusammengestellt, deshalb schließe ich hier alle Bug Reports. Wenn der Fehler weiterhin auftritt, dann öffne bitte eine neue Issue.
