### ISSUE TITLE
Massive Lags + abgeschnittene Welt

### ISSUE THREAD

**Issue by MachiaPulcino** [ToadsworthLP/GronkhsLitW#5]
Hey, ich bin es schon wieder: 

Leider hat sich nun ein weiteres Problem eingeschlichen. Unsere Welt laggt unglaublich stark, trotz guter RAM,CPU und Internetconnection beider Spieler. Zudem ist die Welt bei einer gewissen Reichweite von ungefähr 3 Biomen abgeschnitten ( kein Wasser,keine Erde, nichts.) Gibt es hierfür eine Lösung? :(

**Comment by ToadsworthLP** [comment]
Hat der Serverlog irgendwas auffälliges auspespuckt? Bitte lade den Log auf Pastebin oder so hoch und antworte mit einem Link dorthin, damit ich mir das mal ansehen kann ;D

**Comment by MachiaPulcino** [comment]
Der Server hat mehrmals, oft hintereinander getaktet geantwortet: "Can't keep up! Did the system time change or is the server overloaded?" Und danach die Verzögerung mit dem Ping von so meist 500-16.000 und der Sekundenanzahl. (meist 10-40)
Danke für deine fixe Antwort!

**Comment by ToadsworthLP** [comment]
Sieht trotz allem sehr nach zu schwacher Hardware aus. Könnte aber auch an zu wenig zugeteiltem RAM liegen. Zum Zuteilen von mehr RAM einfach die _start.bat_ bearbeiten und in der Zeile die unterstrichene Zahl zu ändern (zu Erhöhen, hier sind zum Beispiel 2GB zugewiesen)
`java -Xmx**2**G -Xms1G -XX:MaxPermSize=128m -jar "GronkhsLifeInTheWoods.jar" nogui`
Die Datei dann speichern und ausführen.

**Comment by MachiaPulcino** [comment]
Perfekt, mein Kumpel, der den Server für uns "betreibt" wird es mal ausprobieren. 
Vielen lieben Dank! Ich werde mich nochmal melden, ob es geklappt hat oder nicht. :)

**Comment by MachiaPulcino** [comment]
Hallo Toadsworth! Leider hat die erhöhte RAM-Zuweisung nichts verbessertes hervorgebracht. Es wurden bis zu 6 RAM für den Server zugewiesen und keine Änderung wurde hervorgerufen. Interessant wäre vlt. noch zu wissen, dass man 8 Chunks um sich herum laden kann und nur dann Frameeinbrüche bestehen, wenn man sich bewegt. Die Meldung des Serverlogs bleibt im Prinzip die Selbe, auch die Ping- und die Sekundenverzögerung bleiben auf dem selben Level. 
Auch noch interessant ist, dass wir beide durch hinzufügen von Shadern und Texturepacks keine "besseren" Frames oder "schlechtere Lags" bekommen. Es bleibt so, wie es ist. Das schließt zumindest den Hardwaregedanken von dir aus. 
Danke trotzdem bis hierhin für deine Hilfe und wir hoffen, dass du uns auch noch bis zu einer finalen Lösung zur Seite stehst. Liebe Grüße!

**Comment by ToadsworthLP** [comment]
Zu schwache Hardware ist damit eigentlich auszuschließen. Könntest du mir einen Log von Client und Server schicken? Der enthält vielleicht Informationen.

**Comment by MachiaPulcino** [comment]
![img-20160627-wa0025 1](https://cloud.githubusercontent.com/assets/20113674/16395927/9d7958dc-3cbc-11e6-822b-40a36186c096.jpg)
-> Direkt nach dem Start

![img-20160627-wa0026 1](https://cloud.githubusercontent.com/assets/20113674/16395937/aeb1785a-3cbc-11e6-9125-c5e0b37a9110.jpg)
-> "Mitten im Spiel"  ( 30sek.)
![img-20160627-wa0027 1](https://cloud.githubusercontent.com/assets/20113674/16395957/c4f52350-3cbc-11e6-951b-fc118dbfd04c.jpg)
-> Problemerzeugung


Ich hoffe du kannst damit etwas anfangen! LG!

**Comment by ToadsworthLP** [comment]
Die RAM-Zuweisung über eine Veränderung der start.bat ist nicht wirksam, wenn der Server per Doppelklick auf die GronkhsLifeInTheWoods.jar gestartet wird! Deshalb immer die "start.bat" verwenden, dafür ist sie ja da!

**Comment by ToadsworthLP** [comment]
Weil ich hier jetzt schon einige Tage keine Aktivität gesehen habe. schließe ich diese Issue mal. Falls noch Probleme auftauchen öffne einfach eine Neue ;D
