### ISSUE TITLE
LitW Startet nicht

### ISSUE THREAD

**Issue by dwrk94** [ToadsworthLP/GronkhsLitW#53]
seit heute Startet das Spiel nicht mehr, der Technic Launcher ladet kurz, dann blendet er sich aus, wo Minecraft starten sollte.

Hab das "Gronkh's Life in the Woods" Pack installiert und auch immer darüber gestartet.

Hab das Paxk auch schon neu Installiert, hat aber nicht geholfen..

**Comment by ToadsworthLP** [comment]
Ich habe das Pack von Grund auf neu zusammengestellt, deshalb schließe ich hier alle Bug Reports. Wenn der Fehler weiterhin auftritt, dann öffne bitte eine neue Issue.
