### ISSUE TITLE
Minecraft startet nicht

### ISSUE THREAD

**Issue by felix31415** [ToadsworthLP/GronkhsLitW#54]
Hi,

Hab das Mod pack mit der Version 2.4 heruntergeladen hat alles funktioniert. Nun habe ich auf die Version 3.1 upgedated und dann startet minecraft nicht nach dem ich über den Techniklauncher das Mod pack starten will.

mfg

**Comment by ToadsworthLP** [comment]
Ohne Log oder Crashreport kann ich nur raten, aber das sind dir häufigsten Probleme:
1. Java 8 benutzen
2. NVidia-Grafikkartentreiber updaten: http://nvidia.custhelp.com/app/answers/detail/a_id/4378
3. Mehr RAM zuweisen

**Comment by Lightning25** [comment]
Hallo habs versucht zu starten aber es klappt einfach nicht laut Console kam dieser Fehler:

`[B#349] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[B#349] SLF4J: Defaulting to no-operation (NOP) logger implementation
[B#349] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[B#349] Starting download of http://cdn.technicpack.net/platform2/pack-icons/814581.png?1486311658, with 3 tries remaining
[B#349] Starting download of http://cdn.technicpack.net/platform2/pack-icons/814581.png?1486311658, with 3 tries remaining
[B#349] Running C:\Program Files\Java\jre1.8.0_121\bin\javaw.exe -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms10240m -Xmx10240m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -Djava.library.path=C:\Users\ParanoitDJ\AppData\Roaming\.technic\modpacks\life-in-the-woods-extended\bin\natives -Dfml.core.libraries.mirror=http://mirror.technicpack.net/Technic/lib/fml/%s -Dminecraft.applet.TargetDirectory=C:\Users\ParanoitDJ\AppData\Roaming\.technic\modpacks\life-in-the-woods-extended -Djava.net.preferIPv4Stack=true -cp C:\Users\ParanoitDJ\AppData\Roaming\.technic\modpacks\life-in-the-woods-extended\bin\modpack.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\typesafe\config\1.2.1\config-1.2.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\lzma\lzma\0.0.1\lzma-0.0.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\google\guava\guava\17.0\guava-17.0.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\mojang\realms\1.2.9\realms-1.2.9.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\java3d\vecmath\1.3.1\vecmath-1.3.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\google\guava\guava\15.0\guava-15.0.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\mojang\authlib\1.5.13\authlib-1.5.13.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\tv\twitch\twitch\5.16\twitch-5.16.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\modpacks\life-in-the-woods-extended\bin\minecraft.jar net.minecraft.launchwrapper.Launch --username Tesla24 --version 1.7.10-Forge10.13.4.1614-1.7.10 --gameDir C:\Users\ParanoitDJ\AppData\Roaming\.technic\modpacks\life-in-the-woods-extended --assetsDir C:\Users\ParanoitDJ\AppData\Roaming\.technic\assets --assetIndex 1.7.10 --uuid a0f3e6d75d414a32b424d21db96c5915 --accessToken 0d2db424e78642baa1054cb4e98e8e7a --userProperties {} --userType mojang --tweakClass cpw.mods.fml.common.launcher.FMLTweaker --title Gronkh's Life in the Woods --icon C:\Users\ParanoitDJ\AppData\Roaming\.technic\assets\packs\life-in-the-woods-extended\icon.png
[B#349] C:\Program Files\Java\jre1.8.0_121\bin\javaw.exe -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms10240m -Xmx10240m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -Djava.library.path=C:\Users\ParanoitDJ\AppData\Roaming\.technic\modpacks\life-in-the-woods-extended\bin\natives -Dfml.core.libraries.mirror=http://mirror.technicpack.net/Technic/lib/fml/%s -Dminecraft.applet.TargetDirectory=C:\Users\ParanoitDJ\AppData\Roaming\.technic\modpacks\life-in-the-woods-extended -Djava.net.preferIPv4Stack=true -cp C:\Users\ParanoitDJ\AppData\Roaming\.technic\modpacks\life-in-the-woods-extended\bin\modpack.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\typesafe\config\1.2.1\config-1.2.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\lzma\lzma\0.0.1\lzma-0.0.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\google\guava\guava\17.0\guava-17.0.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\mojang\realms\1.2.9\realms-1.2.9.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\java3d\vecmath\1.3.1\vecmath-1.3.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\google\guava\guava\15.0\guava-15.0.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\com\mojang\authlib\1.5.13\authlib-1.5.13.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\cache\tv\twitch\twitch\5.16\twitch-5.16.jar;C:\Users\ParanoitDJ\AppData\Roaming\.technic\modpacks\life-in-the-woods-extended\bin\minecraft.jar net.minecraft.launchwrapper.Launch --username Tesla24 --version 1.7.10-Forge10.13.4.1614-1.7.10 --gameDir C:\Users\ParanoitDJ\AppData\Roaming\.technic\modpacks\life-in-the-woods-extended --assetsDir C:\Users\ParanoitDJ\AppData\Roaming\.technic\assets --assetIndex 1.7.10 --uuid a0f3e6d75d414a32b424d21db96c5915 --accessToken 0d2db424e78642baa1054cb4e98e8e7a --userProperties {} --userType mojang --tweakClass cpw.mods.fml.common.launcher.FMLTweaker --title Gronkh's Life in the Woods --icon C:\Users\ParanoitDJ\AppData\Roaming\.technic\assets\packs\life-in-the-woods-extended\icon.png 
[B#349] Analytics Response [runModpack]: 200
[B#349] Starting download of http://cdn.technicpack.net/platform2/pack-icons/814581.png?1486311658, with 3 tries remaining
[B#349]  [17:39:02] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[B#349]  [17:39:02] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[B#349]  [17:39:02] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[B#349]  [17:39:02] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[B#349]  [17:39:02] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_121, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_121
[B#349]  [17:39:03] [main/WARN] [FML]: The coremod mods.betterfoliage.loader.BetterFoliageLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#349]  [17:39:03] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
`
kann damit aber nichts anfangen

LG Heiko

**Comment by ToadsworthLP** [comment]
@Lighting25 Könntest du mir eventuell einen vollständigen Crashlog statt nur einen Konsolenausschnitt schicken? Damit kann ich leider nicht viel anfangen :/
@felix31514 Haben meine Tipps funktioniert? Wenn nicht bräuchte ich auch von dir einen vollständigen Crasglog.

**Comment by Lightning25** [comment]
er erstellt keine neuen Crashlogs habs nochmal versucht zu starten aber erstellt wird da nichts neuem im Crash report ordner

**Comment by felix31415** [comment]
Hi,

Also jetzt weiß ich nicht mehr woran der Fehler liegt denn jetzt startet es ohne Probleme. Was ich aber noch weiß ist das in den Mods BetterFoliage-MC1.7.10-2.0.14 und CodeChickenCore-1.7.10-1.0.7.47-universal irgendetwas gefunden wurde und dann hat er nicht gestartet.
sorry hab keinen Crashlog.

mfg

**Comment by Lightning25** [comment]
okay nun geht bei mri auch alles wieder nach nem Grafikkarten Update  von meiner Geforce GTX 98 ti... darauf muss man erstmal kommen komische sache Entschuldige Toadsworth  fr die unanehmlichkeiten

**Comment by ToadsworthLP** [comment]
@Lightning25 Das mit dem Grafikkarten-Update habe ich schon weiter oben erwähnt.
Kein Problem, dafür ist der Issue Tracker ja da :)
