### ISSUE TITLE
Inhalte von neuen Mods fehlen teilweise

### ISSUE THREAD

**Issue by traendyaux** [ToadsworthLP/GronkhsLitW#58]
Da ja durch das Update neue Inhalte hinzugefügt wurden, sind diese vorhanden, wenn man eine neue Welt beginnt. Wenn man jedoch in seiner alten Welt weiter spielt, dann sind diese Inhalte nur teilweise da. Mir ist es aufgefallen, da ich nirgends Aluminium gefunden habe weder als Stein Kies oder Busch. (Rezepte dafür finde ich aber) Wenn ich die gleiche Welt aber neu laden lasse, dann sind diese Sachen da. (Aber natürlich mein ganzes erbautes weg) Auch laufen mir da viele andere Kreaturen über den Weg. Wie bekommt man seinen alten Speicherstand so hin, dass alle neuen Inhalte funktionieren?
Vielen Dank dir schon mal im Voraus und ein großes Lob an dich für das zusammen stellen dieses Modpacks. 👍

**Comment by ToadsworthLP** [comment]
In einer alten Welt kann man leider keine neuen Erze und andere IWorldGenerator-basierte Inhalte generieren, außer man kommt in Teile der Welt, die noch nicht generiert wurden. Ab MC1.8.9 gibt es SimpleRetrogen, aber in der 1.7.10 fällt mir da nichts ein. Wie gesagt, wenn du weit genug läufst, kannst du die neuen Erze finden, aber das kann etwas dauern.

**Comment by traendyaux** [comment]
Vielen Dank dir für die schnelle Informationen.
Dann muss ich wohl neu anfangen oder umziehen. 😅 
Hast du eine Ahnung, wie Gronkh das dann macht? (Bin noch nicht so weit bei seinen Folgen, wo  er die neuen Erze hat)
