### ISSUE TITLE
Sehr viele lags und Abstürze

### ISSUE THREAD

**Issue by Tanijathefaun** [ToadsworthLP/GronkhsLitW#6]
Habe sehr heftige Lags erlebt, bei einem Absturz kam dann die Nachricht, dass ein Problem festgestellt wurde und man von seinem Spielstand ein Backup machen sollte (habe leider keinen Screenshot)
Ein Crashbericht ist angehängt, leider kann ich nicht viel mehr dazu sagen. :/
[crash-2016-06-26_17.12.24-server.txt](https://github.com/ToadsworthLP/GronkhsLitW/files/333653/crash-2016-06-26_17.12.24-server.txt)

**Comment by ToadsworthLP** [comment]
Dem Server ist anscheinend der RAM ausgegangen. Startest du den Server per Doppelklick auf die GronkhsLifeInTheWoods.jar oder mit der start.bat ?

**Comment by Tanijathefaun** [comment]
Ich kenne mich mit sowas leider noch nciht so sehr aus...Starte das Programm immer über den TechnicLauncher.
Ich habe aber das Gefühl, dass das Problem mit der Thaumcraft-Erweiterung zusammenhängt, da es ausschließlich auftritt, wenn ich den Bereich meines alten Savegames verlasse und neue Chunks generiert werden (in den alten sind dementsprechend keine Gegenstände aus Thaumcraft enthalten). Würde es zu Problemen mit der Welt kommen, wenn ich die Mod komplett deaktiviere und ohne weiterspiele?

**Comment by ToadsworthLP** [comment]
Sorry, als ich den Server-Crashreport gesehen habe dachte ich nicht dran, dass es sich um den Integrierten Singleplayer-Server handelt XD Jedenfalls sieht es nicht nach einem Fehler mit Thaumcraft aus. Seit dem Update ist aber etwas mehr RAM nötig, versuche mal, mehr zuzuweisen (in den Launcher-Einstellungen > Java-Einstellungen)

**Comment by ToadsworthLP** [comment]
Sollte der obrige Hinweis zu einer Lösung des Problems führen, bitte schließe diesen Report. Oder schreib einfach, wenn es funktioniert hat, dann mach ich das ;D

**Comment by Tanijathefaun** [comment]
Ok, super, werde ich mal testen! :)
Eine Frage hätte ich noch: Seit dem Crash erscheinen die Vorderseiten der Storage-Regale als schwarze Oberfläche, die sich nurnoch bei direktem Fackellicht davor ändert...weißt du, ob das irgendwie zusammenhängt? Shaderwechsel hat nichts gebracht.

**Comment by ToadsworthLP** [comment]
Durch einen Crash kann es manchmal zu Belichtungsproblemen kommen, weil die Chunkdaten manchmal unvollständig oder fehlerhaft gespeichert werden, was sich aber in den meisten Fällen selbst behebt. In deinem Fall platziere einfach irgendeinen Block vor einem Regal und baue ihn wieder ab. Das sollte es beheben!
