### ISSUE TITLE
Mods werden geladen - Spiel startet nicht

### ISSUE THREAD

**Issue by Muck8589** [ToadsworthLP/GronkhsLitW#69]
Hi. 
Ich bin komplett neu :)

Habe mir gerade den Technic Launcher runtergeladen und die LitW 3.5 geladen.
Bei mir passiert folgendes:
Ladebildschirm Forge erscheint
Alle Mods werden initialisiert

Oberer Balken:
Loading - Finishing Up 6/7

Unterer Balken:
Load Complete - Waila 78/98

Ladebildschirm verschwindet

Ende 🗡

Danach passiert nichts mehr.
GIbt es dazu eine Lösung?

Danke im Voraus

Gruß
Muck8589

**Comment by Vapor028** [comment]
Guten Morgen. 
Wie viel RAM hast du bei dem Modpack bzw. dem Technic Launcher zugewiesen? Ich persönlich empfehle da aus Erfahrung 4GB oder mehr.

**Comment by Muck8589** [comment]
Hi @Vapor028 
Ich habe gestern Abend noch ein bisschen rumgesucht und dann die Option der RAM- Zuweisung des Launchers gefunden. Habe 4GB zugewiesen und siehe da, es funktioniert :)
Problem ist also behoben.

Danke für deine Hilfe 👍
