### ISSUE TITLE
Mystcraft Welt  Laggs, Biomeradar geht nicht, 

### ISSUE THREAD

**Issue by sonykill** [ToadsworthLP/GronkhsLitW#7]
der Server laggt extrem wenn eine Mystcraft welt generiert wird .. selbst nach 20 min war der server noch 14000 ms hinter her    der server hat 3-4gb ram ....   ( auf dem gleichen root läuft noch ein feed the beast server der keine probleme macht ( mit sehr viel mehr mods etc .. 100-200 und mystcraft ) der server war dort meist kurz überlastet  und ging dan wieder .. bei dem life in the woods bessert sich garnichts zurzeit ... warschl mods die konkurieren ? 
hinzu kommt noch das das biome radar von biomes o plenty nicht geht ( rechtsklick geht garnicht auch wenn das radar auf ein bestimmtes biome gesetzt wurde durch die escense,

**Comment by ToadsworthLP** [comment]
Zum Biome Radar kann ich nicht viel sagen - ich nutze es nie und hab auch sonst zugegeben nicht viel Ahnung davon - aber Mystcraft ist nunmal ein Leistungskiller am Server, vor allem, wenn viele Mods dabei sind, die z.B. neue Biome hinzufügen (woraus Life in the Woods zu gefühlt 80% besteht). Das hat mit dem World Generator zu tun, mit dem Mystcraft die Welten erstellt. Ist jetzt schwierig zu erklären. Kannst du mir einen Server Log schicken, und auch vielleicht den Namen des FTB-Modpacks, welches du auch auf dem Server hast?

**Comment by ToadsworthLP** [comment]
Wegen Inaktivität schließe ich diese Issue. Falls du doch noch geplant hattest, zu antworten, erstelle bitte eine neue.
