### ISSUE TITLE
Thaumcraft Integration

### ISSUE THREAD

**Issue by Pallony** [ToadsworthLP/GronkhsLitW#8]
Ich habe bei Thaumcraft im Modpack bisher folgende Probleme festgestellt:

1. Das Gravestone Mod speichert beim Spielertot keine Baubles-Items. Das ausgerüstete Baubles Inventar fällt  beim Tot einfach auf den Boden. Die neuste Version des Mods ist nach Aussage des Modautors kompatibel mit Baubles, leider konnte ich das noch nicht testen.
[http://mods.curse.com/mc-mods/minecraft/237071-gravestones-die-classy](http://mods.curse.com/mc-mods/minecraft/237071-gravestones-die-classy)

2. NEI kann die meisten Thaumcraft Rezepte nicht anzeigen. Das Thaumonomicon reicht zum nachlesen, aber eine Thaumcraft-NEI Interaktion ist komfortabler. Ich würde vorschlagen das Thaumcraft NEI Plugin hinzuzufügen, mit dem NEI alle Thaumcraft Rezepte abbilden kann.
Ich habe Version "ThaumcraftNEIPlugin-1.7.10-1.7a" installiert und bisher keine Probleme gehabt.
[http://mods.curse.com/mc-mods/minecraft/225095-thaumcraft-nei-plugins](http://mods.curse.com/mc-mods/minecraft/237071-gravestones-die-classy)

Edit: Links gefixt.

**Comment by ToadsworthLP** [comment]
Da hab ich wohl was beim 2.0 Update vergessen XD
Wird in der nächsten Stunde nachgepatcht ;) Und eine Mod kommt außerdem noch dazu, damit die diversen Mod-Erze nich so out-of-place wirken.
