### ISSUE TITLE
Minecraft doesn't start

### ISSUE THREAD

**Issue by Keith131** [ToadsworthLP/GronkhsLitW#9]
Here is the error log:
[crash-2016-06-28_15.28.14-client.txt](https://github.com/ToadsworthLP/GronkhsLitW/files/337303/crash-2016-06-28_15.28.14-client.txt)

**Comment by ToadsworthLP** [comment]
You're using 32-bit Windows, so you can't allocate enough RAM to Minecraft to use the pack properly. There's nothing I can do for you, your PC is just too weak. Sorry :(
